version: "3.4"
services:
  webapp-test:
    build:
      context: webapp
      dockerfile: Dockerfile
      target: test
    depends_on:
      - webapp-database
  webapp-database:
    image: postgres:14.0-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db